reyestrGovUa:
  url: "https://reyestr.court.gov.ua/"
  pagingInfo:
    itemsPerPage: "1000"
googleSheets:
  tokensDirectoryPath: "tokens"
  applicationName: "Document Synchronisation"
  dataPattern: "yyyy-MM-dd HH:mm"
